### ISSUE TITLE
Missing event onConnectionStateChange in PeerConnection.Observer

### ISSUE THREAD

**Issue by asik** [dmariogatto/xamarin-webrtc#3]
It seems the type
`Xam.WebRtc.Android.PeerConnection.IObserver`
is missing a binding for `onConnectionChange` from `org.webrtc.PeerConnection.Observer` (https://chromium.googlesource.com/external/webrtc/+/master/sdk/android/api/org/webrtc/PeerConnection.java#110).

Using Xam.WebRtc.Android 1.0.32006.

This seems like an important event so it'd be good to support it. Thank you!

**Comment by dmariogatto** [comment]
Thanks for reporting this! Looks like it'll be reasonably simple to add that event. I should be able to make a PR & publish to nuget in the next few days.
