### ISSUE TITLE
Free for Commercial Use

### ISSUE THREAD

**Issue by LumiProj** [dmariogatto/xamarin-webrtc#5]
Hi,

Please guide me can we use this in my commercial project.

Thanks

**Comment by dmariogatto** [comment]
Go for it. This is just a binding library over the top of the native open source WebRTC libraries,

- [Android | WebRTC](https://webrtc.github.io/webrtc-org/native-code/android/)
- [iOS | WebRTC](https://webrtc.github.io/webrtc-org/native-code/ios/)
- [Licence | WebRTC](https://webrtc.github.io/webrtc-org/license/software/)
